# Generated by Django 3.1.5 on 2021-01-19 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auto_20210119_2109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='reserve',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
