# Generated by Django 3.1.5 on 2021-01-19 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_auto_20210119_2110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='bid_timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
