# Generated by Django 3.1.5 on 2021-01-29 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_auto_20210128_2239'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='last_modified',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
