# Generated by Django 3.1.5 on 2021-01-29 19:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_auto_20210129_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchedlisting',
            name='watcher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='watching', to=settings.AUTH_USER_MODEL),
        ),
    ]
