# Generated by Django 3.1.5 on 2021-01-25 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_auto_20210125_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='description',
            field=models.TextField(max_length=350),
        ),
        migrations.AlterField(
            model_name='listing',
            name='imageURL',
            field=models.URLField(blank=True, max_length=250, null=True),
        ),
    ]
