# Generated by Django 3.1.5 on 2021-01-29 20:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_auto_20210129_1938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchedlisting',
            name='item',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='auctions.listing'),
        ),
        migrations.RemoveField(
            model_name='watchedlisting',
            name='watcher',
        ),
        migrations.AddField(
            model_name='watchedlisting',
            name='watcher',
            field=models.ManyToManyField(null=True, related_name='watching', to=settings.AUTH_USER_MODEL),
        ),
    ]
