# Generated by Django 3.1.5 on 2021-01-26 21:55

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_auto_20210125_1801'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', multiselectfield.db.fields.MultiSelectField(choices=[('cat', 'Cats'), ('dog', 'Dogs'), ('bird', 'Birds'), ('reptile', 'Reptiles'), ('hammy', 'Hamsters'), ('gween', 'Guinea Pigs'), ('gerbil', 'Gerbils'), ('horse', 'Horses'), ('other', 'Other Pets')], max_length=51)),
                ('item', models.ManyToManyField(blank=True, related_name='categories', to='auctions.Listing')),
            ],
        ),
    ]
