# Generated by Django 3.1.5 on 2021-01-29 20:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_auto_20210129_2018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchedlisting',
            name='watcher',
            field=models.ManyToManyField(related_name='watching', to=settings.AUTH_USER_MODEL),
        ),
    ]
