# Generated by Django 3.1.5 on 2021-01-26 22:42

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='pet_type',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('c', 'Cats'), ('d', 'Dogs'), ('b', 'Birds'), ('r', 'Reptiles'), ('s', 'Small Critters'), ('h', 'Horses'), ('o', 'Other Pets')], default='o', max_length=13),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='category',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('fu', 'Funny'), ('ch', 'Famous Characters'), ('sc', 'Scary'), ('fa', 'Fancy'), ('sp', 'Sporty'), ('ce', 'Celebrations'), ('ho', 'Holidays'), ('an', 'Animals'), ('jo', 'Jobs'), ('wh', 'Why God, Why?'), ('ac', 'Accessories'), ('fo', 'Foody')], max_length=35, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='item',
            field=models.ManyToManyField(related_name='categories', to='auctions.Listing'),
        ),
    ]
