# Generated by Django 3.1.5 on 2021-01-26 23:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_auto_20210126_2242'),
    ]

    operations = [
        migrations.CreateModel(
            name='PetType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pet_type', models.CharField(choices=[('A', 'Any Pet'), ('C', 'Cat'), ('D', 'Dog'), ('B', 'Bird'), ('R', 'Reptile'), ('S', 'Small Critter'), ('H', 'Horse'), ('O', 'Other Pet')], default='A', max_length=1)),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pet_type_items', to='auctions.listing')),
            ],
        ),
        migrations.AlterField(
            model_name='comment',
            name='commenter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments_by_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='comment',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments_by_topic', to='auctions.listing'),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
