# Generated by Django 3.1.5 on 2021-01-29 21:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_auto_20210129_2019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchedlisting',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='watched', to='auctions.listing'),
        ),
    ]
