# Generated by Django 3.1.5 on 2021-01-29 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0013_auto_20210129_2250'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-comment_timestamp']},
        ),
    ]
